import { Transaction } from "@/types/transaction";

export const transactionsData: Transaction[] = [
  {
    id: "TRX001",
    description: "فروش محصول دیجیتال - دوره Next.js",
    category: "فروش آنلاین",
    date: "1404/09/18",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "کارت به کارت",
  },
  {
    id: "TRX002",
    description: "خرید سرور ابری - DigitalOcean",
    category: "زیرساخت",
    date: "1404/09/17",
    amount: 2500000,
    type: "expense",
    status: "completed",
    paymentMethod: "درگاه بانکی",
  },
  {
    id: "TRX003",
    description: "پرداخت حقوق تیم توسعه",
    category: "حقوق و دستمزد",
    date: "1404/09/15",
    amount: 35000000,
    type: "expense",
    status: "pending",
    paymentMethod: "واریز بانکی",
  },
  {
    id: "TRX004",
    description: "درآمد پروژه فریلنسری - طراحی UI/UX",
    category: "پروژه‌های جانبی",
    date: "1404/09/14",
    amount: 8500000,
    type: "income",
    status: "completed",
    paymentMethod: "پی‌پال",
  },
  {
    id: "TRX005",
    description: "خرید لایسنس نرم‌افزار Adobe Creative Cloud",
    category: "نرم‌افزار",
    date: "1404/09/12",
    amount: 1200000,
    type: "expense",
    status: "failed",
    paymentMethod: "کارت اعتباری",
  },
  {
    id: "TRX006",
    description: "فروش اشتراک ماهانه اپلیکیشن",
    category: "درآمد دوره‌ای",
    date: "1404/09/10",
    amount: 4500000,
    type: "income",
    status: "completed",
    paymentMethod: "درگاه زرین‌پال",
  },
  {
    id: "TRX007",
    description: "هزینه تبلیغات Google Ads",
    category: "بازاریابی",
    date: "1404/09/08",
    amount: 3800000,
    type: "expense",
    status: "completed",
    paymentMethod: "کارت بانکی",
  },
  {
    id: "TRX008",
    description: "درآمد مشاوره تخصصی - 3 ساعت",
    category: "خدمات مشاوره",
    date: "1404/09/05",
    amount: 6000000,
    type: "income",
    status: "pending",
    paymentMethod: "واریز نقدی",
  },
];
