import { Transaction } from "@/types/transaction";

export const transactionsData: Transaction[] = [
  {
    id: "TRX001",
    description: "فروش محصول دیجیتال - دوره Next.js",
    category: "فروش آنلاین",
    date: "1404/09/18",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX002",
    description: "خرید سرور ابری - DigitalOcean",
    category: "زیرساخت",
    date: "1404/09/17",
    amount: 2500000,
    type: "expense",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX003",
    description: "پرداخت حقوق تیم توسعه",
    category: "حقوق و دستمزد",
    date: "1404/09/15",
    amount: 35000000,
    type: "expense",
    status: "pending",
    paymentMethod: "cash",
  },
  {
    id: "TRX004",
    description: "درآمد پروژه فریلنسری - طراحی UI/UX",
    category: "پروژه‌های جانبی",
    date: "1404/09/14",
    amount: 8500000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX005",
    description: "خرید لایسنس Adobe Creative Cloud",
    category: "نرم‌افزار",
    date: "1404/09/12",
    amount: 1200000,
    type: "expense",
    status: "failed",
    paymentMethod: "online",
  },
  {
    id: "TRX006",
    description: "فروش اشتراک ماهانه اپلیکیشن",
    category: "درآمد دوره‌ای",
    date: "1404/09/10",
    amount: 4500000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX007",
    description: "هزینه تبلیغات Google Ads",
    category: "بازاریابی",
    date: "1404/09/08",
    amount: 3800000,
    type: "expense",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX008",
    description: "درآمد مشاوره تخصصی - 3 ساعت",
    category: "خدمات مشاوره",
    date: "1404/09/05",
    amount: 6000000,
    type: "income",
    status: "pending",
    paymentMethod: "online",
  },
  {
    id: "TRX009",
    description: "تمدید دامنه سایت شرکتی",
    category: "زیرساخت",
    date: "1404/09/03",
    amount: 450000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX010",
    description: "درآمد فروش قالب اختصاصی",
    category: "فروش آنلاین",
    date: "1404/09/01",
    amount: 7200000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX011",
    description: "هزینه تولید محتوا اینستاگرام",
    category: "بازاریابی",
    date: "1404/08/29",
    amount: 2100000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX012",
    description: "درآمد طراحی داشبورد ادمین",
    category: "پروژه‌های جانبی",
    date: "1404/08/27",
    amount: 9800000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX013",
    description: "خرید اکانت GitHub Copilot",
    category: "نرم‌افزار",
    date: "1404/08/25",
    amount: 900000,
    type: "expense",
    status: "completed",
    paymentMethod: "cash",
  },
  {
    id: "TRX014",
    description: "درآمد پشتیبانی ماهانه سایت",
    category: "درآمد دوره‌ای",
    date: "1404/08/23",
    amount: 3000000,
    type: "income",
    status: "pending",
    paymentMethod: "cash",
  },
  {
    id: "TRX015",
    description: "هزینه خرید UI Kit",
    category: "نرم‌افزار",
    date: "1404/08/21",
    amount: 650000,
    type: "expense",
    status: "completed",
    paymentMethod: "cash",
  },
  {
    id: "TRX016",
    description: "درآمد فروش افزونه اختصاصی",
    category: "فروش آنلاین",
    date: "1404/08/19",
    amount: 5600000,
    type: "income",
    status: "completed",
    paymentMethod: "cash",
  },
  {
    id: "TRX017",
    description: "پرداخت مالیات دوره‌ای",
    category: "مالیات",
    date: "1404/08/17",
    amount: 7800000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX018",
    description: "درآمد آموزش خصوصی React",
    category: "آموزش",
    date: "1404/08/15",
    amount: 4200000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX019",
    description: "هزینه ابزار مدیریت پروژه",
    category: "نرم‌افزار",
    date: "1404/08/13",
    amount: 1100000,
    type: "expense",
    status: "failed",
    paymentMethod: "cash",
  },
  {
    id: "TRX020",
    description: "درآمد قرارداد پشتیبانی سالانه",
    category: "قراردادها",
    date: "1404/08/10",
    amount: 24000000,
    type: "income",
    status: "completed",
    paymentMethod: "cash",
  },
];
