// config/transaction-data.ts

import { Transaction } from "@/types/transaction";

export const transactionsData: Transaction[] = [
  // ===== ماه آذر (09) =====
  {
    id: "TRX001",
    description: "حقوق ماهانه",
    category: "salary",
    date: "1404/09/18",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX002",
    description: "خرید مواد غذایی",
    category: "food",
    date: "1404/09/17",
    amount: 2500000,
    type: "expense",
    status: "completed",
    paymentMethod: "cash",
  },
  {
    id: "TRX003",
    description: "پروژه فریلنسری",
    category: "freelance",
    date: "1404/09/16",
    amount: 8500000,
    type: "income",
    status: "pending",
    paymentMethod: "online",
  },
  {
    id: "TRX004",
    description: "کرایه تاکسی",
    category: "transport",
    date: "1404/09/15",
    amount: 450000,
    type: "expense",
    status: "completed",
    paymentMethod: "cash",
  },
  {
    id: "TRX005",
    description: "خرید لباس زمستانی",
    category: "shopping",
    date: "1404/09/14",
    amount: 3200000,
    type: "expense",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX006",
    description: "قبض برق",
    category: "bills",
    date: "1404/09/13",
    amount: 480000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX007",
    description: "ویزیت دکتر",
    category: "health",
    date: "1404/09/12",
    amount: 900000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX008",
    description: "بازی و سرگرمی",
    category: "entertainment",
    date: "1404/09/11",
    amount: 600000,
    type: "expense",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX009",
    description: "خرید کتاب آموزشی",
    category: "education",
    date: "1404/09/10",
    amount: 750000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX010",
    description: "اجاره خانه",
    category: "home",
    date: "1404/09/09",
    amount: 10000000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX011",
    description: "پرداخت بیمه",
    category: "insurance",
    date: "1404/09/08",
    amount: 1200000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX012",
    description: "کمک مالی",
    category: "gifts",
    date: "1404/09/07",
    amount: 500000,
    type: "expense",
    status: "completed",
    paymentMethod: "cash",
  },
  {
    id: "TRX013",
    description: "هزینه متفرقه",
    category: "expenseOther",
    date: "1404/09/06",
    amount: 300000,
    type: "expense",
    status: "failed",
    paymentMethod: "cash",
  },
  {
    id: "TRX014",
    description: "درآمد کسب‌وکار",
    category: "business",
    date: "1404/09/05",
    amount: 12000000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX015",
    description: "سود سرمایه‌گذاری",
    category: "investment",
    date: "1404/09/04",
    amount: 4200000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX016",
    description: "دریافت اجاره",
    category: "rental",
    date: "1404/09/03",
    amount: 7000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX017",
    description: "پاداش پایان پروژه",
    category: "bonus",
    date: "1404/09/02",
    amount: 3000000,
    type: "income",
    status: "pending",
    paymentMethod: "online",
  },
  {
    id: "TRX018",
    description: "هدیه تولد دریافتی",
    category: "giftReceived",
    date: "1404/09/01",
    amount: 1500000,
    type: "income",
    status: "completed",
    paymentMethod: "cash",
  },

  // ===== ماه آبان (08) =====
  {
    id: "TRX019",
    description: "حقوق آبان",
    category: "salary",
    date: "1404/08/21",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX020",
    description: "خرید مواد غذایی",
    category: "food",
    date: "1404/08/15",
    amount: 2200000,
    type: "expense",
    status: "completed",
    paymentMethod: "cash",
  },
  {
    id: "TRX021",
    description: "قبض آب",
    category: "bills",
    date: "1404/08/10",
    amount: 350000,
    type: "expense",
    status: "completed",
    paymentMethod: "online",
  },

  // ===== ماه مهر (07) =====
  {
    id: "TRX022",
    description: "حقوق مهر",
    category: "salary",
    date: "1404/07/20",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX023",
    description: "پروژه فریلنس",
    category: "freelance",
    date: "1404/07/15",
    amount: 7000000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX024",
    description: "خرید لوازم منزل",
    category: "home",
    date: "1404/07/10",
    amount: 4500000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },

  // ===== ماه شهریور (06) =====
  {
    id: "TRX025",
    description: "حقوق شهریور",
    category: "salary",
    date: "1404/06/18",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX026",
    description: "خرید کتاب",
    category: "education",
    date: "1404/06/12",
    amount: 850000,
    type: "expense",
    status: "completed",
    paymentMethod: "online",
  },

  // ===== ماه مرداد (05) =====
  {
    id: "TRX027",
    description: "حقوق مرداد",
    category: "salary",
    date: "1404/05/20",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX028",
    description: "مسافرت",
    category: "entertainment",
    date: "1404/05/10",
    amount: 5000000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },

  // ===== ماه تیر (04) =====
  {
    id: "TRX029",
    description: "حقوق تیر",
    category: "salary",
    date: "1404/04/19",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX030",
    description: "تعمیر ماشین",
    category: "transport",
    date: "1404/04/15",
    amount: 3200000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },

  // ===== ماه خرداد (03) =====
  {
    id: "TRX031",
    description: "حقوق خرداد",
    category: "salary",
    date: "1404/03/21",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX032",
    description: "درآمد کسب‌وکار",
    category: "business",
    date: "1404/03/15",
    amount: 10000000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX033",
    description: "خرید لباس",
    category: "shopping",
    date: "1404/03/10",
    amount: 2800000,
    type: "expense",
    status: "completed",
    paymentMethod: "card",
  },

  // ===== ماه اردیبهشت (02) =====
  {
    id: "TRX034",
    description: "حقوق اردیبهشت",
    category: "salary",
    date: "1404/02/20",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX035",
    description: "قبض تلفن",
    category: "bills",
    date: "1404/02/15",
    amount: 600000,
    type: "expense",
    status: "completed",
    paymentMethod: "online",
  },

  // ===== ماه فروردین (01) =====
  {
    id: "TRX036",
    description: "حقوق فروردین",
    category: "salary",
    date: "1404/01/18",
    amount: 15000000,
    type: "income",
    status: "completed",
    paymentMethod: "card",
  },
  {
    id: "TRX037",
    description: "خرید عیدانه",
    category: "shopping",
    date: "1404/01/10",
    amount: 5000000,
    type: "expense",
    status: "completed",
    paymentMethod: "cash",
  },
  {
    id: "TRX038",
    description: "پروژه فریلنس",
    category: "freelance",
    date: "1404/01/25",
    amount: 9000000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX038",
    description: "پروژه فریلنس",
    category: "freelance",
    date: "1404/01/25",
    amount: 9000000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX039",
    description: "پروژه فریلنس",
    category: "freelance",
    date: "1404/01/25",
    amount: 9000000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX040",
    description: "پروژه فریلنس",
    category: "freelance",
    date: "1404/01/25",
    amount: 9000000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
  {
    id: "TRX041",
    description: "پروژه فریلنس",
    category: "freelance",
    date: "1404/01/25",
    amount: 9000000,
    type: "income",
    status: "completed",
    paymentMethod: "online",
  },
];
